"""Project-wide configurable runtime parameters for OpenSpaceEGSE."""


EGSE_SERIAL_PORT_DEFAULT = "/dev/ttyUSB0"
EGSE_SERIAL_BAUDRATE_DEFAULT = 115200
EGSE_SERIAL_MAX_READ_SIZE = 4096

GUI_PLOT_HISTORY_LENGTH = 200
GUI_RX_POLL_INTERVAL_S = 0.02
GUI_UPDATE_INTERVAL_MS = 200
GUI_SIM_FREQUENCY_OPTIONS_HZ = (0.5, 1.0, 2.0, 5.0)
GUI_SIM_FREQUENCY_DEFAULT_INDEX = 1
GUI_EVENT_LOG_TO_FILE_DEFAULT = False
GUI_EVENT_LOG_FILE_DEFAULT = "egse_events.log"

CCSDS_DEFAULT_SPACECRAFT_ID = 1
CCSDS_DEFAULT_VIRTUAL_CHANNEL_ID = 0
CCSDS_DEFAULT_TC_APID = 100
CCSDS_DEFAULT_TM_APID = 200

SIM_TELEMETRY_STATUS_CYCLE = 5

SIM_TEMPERATURE_BASE_CENTI_C = 2000
SIM_TEMPERATURE_STEP_CENTI_C = 25
SIM_TEMPERATURE_SPAN_SAMPLES = 40

SIM_VOLTAGE_BASE_MV = 4800
SIM_VOLTAGE_STEP_MV = 8
SIM_VOLTAGE_SPAN_SAMPLES = 25

SIM_CAPACITY_BASE_DECI_PCT = 900
SIM_CAPACITY_DECREMENT_PER_SAMPLE = 1
SIM_CAPACITY_SPAN_SAMPLES = 120
